[project]
name = "sdoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.0",
    "mistune>=3.1.2",
]
